using System.Collections.Generic;
using Terraria.ID;
using Terraria.GameContent.ItemDropRules;

namespace TerrariaFlagRandomizer.Common.Sets
{
    public class TieredItemSets
    {
        // Pre-Skeletron: Copper, Tin, Iron, Lead, Silver, Tungsten, Gold, Platinum, Demonite, Crimtane, Meteorite
        public static IItemDropRule[] PreSkeletronBars = new IItemDropRule[11]
        {
            ItemDropRule.Common(ItemID.CopperBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.TinBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.IronBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.LeadBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.SilverBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.TungstenBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.GoldBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.PlatinumBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.DemoniteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.CrimtaneBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.MeteoriteBar, minimumDropped: 15, maximumDropped: 35)
        };

        // Post-Skeletron: Demonite, Crimtane, Meteorite, Hellstone
        public static IItemDropRule[] PostSkeletronBars = new IItemDropRule[4]
        {
            ItemDropRule.Common(ItemID.DemoniteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.CrimtaneBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.MeteoriteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.HellstoneBar, minimumDropped: 15, maximumDropped: 35)
        };

        // Hardmode: Cobalt, Palladium, Mythril, Orichalcum, Adamantite, Titanium
        public static IItemDropRule[] HardmodeBars = new IItemDropRule[6]
        {
            ItemDropRule.Common(ItemID.CobaltBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.PalladiumBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.MythrilBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.OrichalcumBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.AdamantiteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.TitaniumBar, minimumDropped: 15, maximumDropped: 35)
        };

        // Post-Mechs: Adamantite, Titanium, Hallowed, Chlorophyte
        public static IItemDropRule[] PostMechBars = new IItemDropRule[4]
        {
            ItemDropRule.Common(ItemID.AdamantiteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.TitaniumBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.HallowedBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.ChlorophyteBar, minimumDropped: 15, maximumDropped: 35)
        };

        // Post-Planters: Chlorophyte, Shroomite, Spectre
        public static IItemDropRule[] PostPlanteraBars = new IItemDropRule[3]
        {
            ItemDropRule.Common(ItemID.ChlorophyteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.ShroomiteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.SpectreBar, minimumDropped: 15, maximumDropped: 35)
        };

        // Post-Golem: Chlorophyte, Shroomite, Spectre
        public static IItemDropRule[] PostGolemBars = new IItemDropRule[3]
        {
            ItemDropRule.Common(ItemID.ChlorophyteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.ShroomiteBar, minimumDropped: 15, maximumDropped: 35),
            ItemDropRule.Common(ItemID.SpectreBar, minimumDropped: 15, maximumDropped: 35)
        };

        public static IItemDropRule[] PreSkeletronMaterials = new IItemDropRule[24]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FallenStar, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Stinger, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.Vine, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.JungleSpores, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Gel, minimumDropped: 10, maximumDropped: 25),
            ItemDropRule.Common(ItemID.Lens, minimumDropped: 1, maximumDropped: 5),
            ItemDropRule.Common(ItemID.BlackLens, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Amethyst, minimumDropped: 5, maximumDropped: 7),
            ItemDropRule.Common(ItemID.Topaz, minimumDropped: 5, maximumDropped: 7),
            ItemDropRule.Common(ItemID.Emerald, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Sapphire, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Ruby, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Diamond, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.Amber, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.FossilOre, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SiltBlock, minimumDropped: 20, maximumDropped: 40),
            ItemDropRule.Common(ItemID.SlushBlock, minimumDropped: 20, maximumDropped: 40),
            ItemDropRule.Common(ItemID.Hook, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.RottenChunk, minimumDropped: 3, maximumDropped: 6),
            ItemDropRule.Common(ItemID.VileMushroom, minimumDropped: 1, maximumDropped: 2),
            ItemDropRule.Common(ItemID.Vertebrae, minimumDropped: 3, maximumDropped: 6),
            ItemDropRule.Common(ItemID.ViciousMushroom, minimumDropped: 1, maximumDropped: 2),
            ItemDropRule.Common(ItemID.Cobweb, minimumDropped: 14, maximumDropped: 28)
        };

        public static IItemDropRule[] PostSkeletronMaterials = new IItemDropRule[14]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FallenStar, minimumDropped: 1, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Stinger, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.Vine, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.JungleSpores, minimumDropped: 2, maximumDropped: 5),
            ItemDropRule.Common(ItemID.BlackLens, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Sapphire, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Ruby, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.Diamond, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.Amber, minimumDropped: 1, maximumDropped: 3),
            ItemDropRule.Common(ItemID.FossilOre, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.Cobweb, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.Bone, minimumDropped: 20, maximumDropped: 40),
            ItemDropRule.Common(ItemID.Obsidian, minimumDropped: 10, maximumDropped: 15)
        };

        public static IItemDropRule[] HardmodeMaterials = new IItemDropRule[17]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CursedFlame, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.Ichor, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.PixieDust, minimumDropped: 10, maximumDropped: 20),
            ItemDropRule.Common(ItemID.CrystalShard, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SpiderFang, minimumDropped: 3, maximumDropped: 5),
            ItemDropRule.Common(ItemID.SoulofLight, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SoulofNight, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SoulofFlight, minimumDropped: 15, maximumDropped: 20),
            ItemDropRule.Common(ItemID.AdamantiteOre, minimumDropped: 30, maximumDropped: 30),
            ItemDropRule.Common(ItemID.TitaniumOre, minimumDropped: 30, maximumDropped: 30),
            ItemDropRule.Common(ItemID.BlackLens, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.DarkShard, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.LightShard, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FrostCore, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.AncientBattleArmorMaterial, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.TruffleWorm, minimumDropped: 1, maximumDropped: 1)
        };

        public static IItemDropRule[] PostMechMaterials = new IItemDropRule[15]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.LifeFruit, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CursedFlame, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.Ichor, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.PixieDust, minimumDropped: 10, maximumDropped: 20),
            ItemDropRule.Common(ItemID.CrystalShard, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SoulofLight, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SoulofNight, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.SoulofFlight, minimumDropped: 15, maximumDropped: 20),
            ItemDropRule.Common(ItemID.BlackLens, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.TurtleShell, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.SoulofMight, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.SoulofSight, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.SoulofFright, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.TruffleWorm, minimumDropped: 1, maximumDropped: 1)
        };

        public static IItemDropRule[] PostPlanteraMaterials = new IItemDropRule[18]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.LifeFruit, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CursedFlame, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.Ichor, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.CrystalShard, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.TurtleShell, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.SoulofMight, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.SoulofSight, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.SoulofFright, minimumDropped: 30, maximumDropped: 50),
            ItemDropRule.Common(ItemID.JungleKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CorruptionKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CrimsonKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.HallowedKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FrozenKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.DungeonDesertKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Ectoplasm, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.BrokenHeroSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.TruffleWorm, minimumDropped: 1, maximumDropped: 1)
        };

        public static IItemDropRule[] PostGolemMaterials = new IItemDropRule[13]
        {
            ItemDropRule.Common(ItemID.LifeCrystal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.LifeFruit, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.TurtleShell, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.JungleKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CorruptionKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.CrimsonKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.HallowedKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FrozenKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.DungeonDesertKey, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Ectoplasm, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.BrokenHeroSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.BeetleHusk, minimumDropped: 5, maximumDropped: 10),
            ItemDropRule.Common(ItemID.TruffleWorm, minimumDropped: 1, maximumDropped: 1)
        };

        public static readonly int[] PreSkeletronWeapons = new int[139] {
            ItemID.IronBroadsword,
            ItemID.IronShortsword,
            ItemID.DemonBow,
            ItemID.LightsBane,
            ItemID.EnchantedBoomerang,
            ItemID.Vilethorn,
            ItemID.Starfury,
            ItemID.FlintlockPistol,
            ItemID.Musket,
            ItemID.Minishark,
            ItemID.IronBow,
            ItemID.SpaceGun,
            ItemID.Harpoon,
            ItemID.SpikyBall,
            ItemID.BallOHurt,
            ItemID.Grenade,
            ItemID.BreathingReed,
            ItemID.BladeofGrass,
            ItemID.ThornChakram,
            ItemID.StarCannon,
            ItemID.BluePhaseblade,
            ItemID.RedPhaseblade,
            ItemID.GreenPhaseblade,
            ItemID.PurplePhaseblade,
            ItemID.WhitePhaseblade,
            ItemID.YellowPhaseblade,
            ItemID.Sandgun,
            ItemID.Trident,
            ItemID.PoisonedKnife,
            ItemID.Ruler,
            ItemID.IceBoomerang,
            ItemID.IceBlade,
            ItemID.AmethystStaff,
            ItemID.TopazStaff,
            ItemID.SapphireStaff,
            ItemID.EmeraldStaff,
            ItemID.RubyStaff,
            ItemID.DiamondStaff,
            ItemID.BloodButcherer,
            ItemID.TendonBow,
            ItemID.TheUndertaker,
            ItemID.TheMeatball,
            ItemID.TheRottedFork,
            ItemID.Boomstick,
            ItemID.Blowgun,
            ItemID.EnchantedSword,
            ItemID.BeeGun,
            ItemID.BeeKeeper,
            ItemID.Beenade,
            ItemID.BoneSword,
            ItemID.CrimsonRod,
            ItemID.ZombieArm,
            ItemID.SlimeStaff,
            ItemID.SnowballCannon,
            ItemID.ChainKnife,
            ItemID.Sickle,
            ItemID.RottenEgg,
            ItemID.BloodyMachete,
            ItemID.BladedGlove,
            ItemID.RedRyder,
            ItemID.CandyCaneSword,
            ItemID.StarAnise,
            ItemID.FruitcakeChakram,
            ItemID.Revolver,
            ItemID.Katana,
            ItemID.PurpleClubberfish,
            ItemID.Swordfish,
            ItemID.HornetStaff,
            ItemID.MolotovCocktail,
            ItemID.FalconBlade,
            ItemID.BeesKnees,
            ItemID.Javelin,
            ItemID.BouncyGrenade,
            ItemID.FrostDaggerfish,
            ItemID.Code1,
            ItemID.CorruptYoyo,
            ItemID.CrimsonYoyo,
            ItemID.JungleYoyo,
            ItemID.Cascade,
            ItemID.Rally,
            ItemID.DyeTradersScimitar,
            ItemID.PainterPaintballGun,
            ItemID.StylistKilLaKillScissorsIWish,
            ItemID.AmberStaff,
            ItemID.BoneJavelin,
            ItemID.BoneDagger,
            ItemID.PlatinumBow,
            ItemID.PlatinumShortsword,
            ItemID.PlatinumBroadsword,
            ItemID.TungstenBow,
            ItemID.TungstenShortsword,
            ItemID.TungstenBroadsword,
            ItemID.LeadBow,
            ItemID.LeadShortsword,
            ItemID.LeadBroadsword,
            ItemID.TinBow,
            ItemID.TinShortsword,
            ItemID.TinBroadsword,
            ItemID.CopperBow,
            ItemID.CopperShortsword,
            ItemID.CopperBroadsword,
            ItemID.SilverBow,
            ItemID.SilverShortsword,
            ItemID.SilverBroadsword,
            ItemID.GoldBow,
            ItemID.GoldShortsword,
            ItemID.GoldBroadsword,
            ItemID.PartyGirlGrenade,
            ItemID.AntlionClaw,
            ItemID.DD2FlameburstTowerT1Popper,
            ItemID.AleThrowingGlove,
            ItemID.DD2BallistraTowerT1Popper,
            ItemID.DD2LightningAuraT1Popper,
            ItemID.DD2ExplosiveTrapT1Popper,
            ItemID.ThunderSpear,
            ItemID.ThunderStaff,
            ItemID.Terragrim,
            ItemID.OrangePhaseblade,
            ItemID.VampireFrogStaff,
            ItemID.BabyBirdStaff,
            ItemID.PaperAirplaneA,
            ItemID.PaperAirplaneB,
            ItemID.ZapinatorGray,
            ItemID.BloodRainBow,
            ItemID.Gladius,
            ItemID.BlandWhip,
            ItemID.GravediggerShovel,
            ItemID.Shroomerang,
            ItemID.CombatWrench,
            ItemID.ThornWhip,
            ItemID.Mace,
            ItemID.FlamingMace,
            ItemID.FlinxStaff,
            ItemID.TentacleSpike,
            ItemID.BatBat,
            ItemID.AbigailsFlower,
            ItemID.PewMaticHorn,
            ItemID.WeatherPain,
            ItemID.HoundiusShootius
        };

        public static readonly int[] PostSkeletronWeapons = new int[26]
        {
            ItemID.FlowerofFire,
            ItemID.MagicMissile,
            ItemID.Flamarang,
            ItemID.MoltenFury,
            ItemID.FieryGreatsword,
            ItemID.Bone,
            ItemID.Muramasa,
            ItemID.AquaScepter,
            ItemID.BlueMoon,
            ItemID.Handgun,
            ItemID.WaterBolt,
            ItemID.Flamelash,
            ItemID.PhoenixBlaster,
            ItemID.Sunfury,
            ItemID.DemonScythe,
            ItemID.NightsEdge,
            ItemID.DarkLance,
            ItemID.BookofSkulls,
            ItemID.ImpStaff,
            ItemID.HellwingBow,
            ItemID.Valor,
            ItemID.ZapinatorGray,
            ItemID.QuadBarrelShotgun,
            ItemID.TragicUmbrella,
            ItemID.FireWhip,
            ItemID.BoneWhip
        };

        public static readonly int[] HardmodeWeapons = new int[91]
        {
            ItemID.DaoofPow,
            ItemID.MythrilHalberd,
            ItemID.AdamantiteGlaive,
            ItemID.BreakerBlade,
            ItemID.ClockworkAssaultRifle,
            ItemID.CobaltRepeater,
            ItemID.MythrilRepeater,
            ItemID.AdamantiteRepeater,
            ItemID.AdamantiteSword,
            ItemID.CobaltSword,
            ItemID.MythrilSword,
            ItemID.IceRod,
            ItemID.LaserRifle,
            ItemID.MagicDagger,
            ItemID.CrystalStorm,
            ItemID.CursedFlames,
            ItemID.Shotgun,
            ItemID.CobaltNaginata,
            ItemID.Cutlass,
            ItemID.Frostbrand,
            ItemID.Marrow,
            ItemID.BeamSword,
            ItemID.IceBow,
            ItemID.FrostStaff,
            ItemID.CoinGun,
            ItemID.PalladiumSword,
            ItemID.PalladiumPike,
            ItemID.PalladiumRepeater,
            ItemID.OrichalcumSword,
            ItemID.OrichalcumHalberd,
            ItemID.OrichalcumRepeater,
            ItemID.TitaniumSword,
            ItemID.TitaniumTrident,
            ItemID.TitaniumRepeater,
            ItemID.NimbusRod,
            ItemID.FlowerofFrost,
            ItemID.Uzi,
            ItemID.IceSickle,
            ItemID.PoisonStaff,
            ItemID.KOCannon,
            ItemID.Bananarang,
            ItemID.GoldenShower,
            ItemID.Gatligator,
            ItemID.ObsidianSwordfish,
            ItemID.QueenSpiderStaff,
            ItemID.Anchor,
            ItemID.SpiderStaff,
            ItemID.PirateStaff,
            ItemID.MeteorStaff,
            ItemID.SoulDrain,
            ItemID.DartPistol,
            ItemID.DartRifle,
            ItemID.ChainGuillotines,
            ItemID.FetidBaghnakhs,
            ItemID.ClingerStaff,
            ItemID.DaedalusStormbow,
            ItemID.FlyingKnife,
            ItemID.CrystalVileShard,
            ItemID.ShadowFlameBow,
            ItemID.ShadowFlameHexDoll,
            ItemID.ShadowFlameKnife,
            ItemID.CrystalSerpent,
            ItemID.Toxikarp,
            ItemID.Bladetongue,
            ItemID.SlapHand,
            ItemID.MedusaHead,
            ItemID.Chik,
            ItemID.Amarok,
            ItemID.HelFire,
            ItemID.FormatC,
            ItemID.Gradient,
            ItemID.TaxCollectorsStickOfDoom,
            ItemID.BluePhasesaber,
            ItemID.RedPhasesaber,
            ItemID.GreenPhasesaber,
            ItemID.PurplePhasesaber,
            ItemID.WhitePhasesaber,
            ItemID.YellowPhasesaber,
            ItemID.SpiritFlame,
            ItemID.SkyFracture,
            ItemID.OnyxBlaster,
            ItemID.OrangePhasesaber,
            ItemID.SanguineStaff,
            ItemID.SharpTears,
            ItemID.DripplerFlail,
            ItemID.ZapinatorOrange,
            ItemID.Smolstar,
            ItemID.BouncingShield,
            ItemID.JoustingLance,
            ItemID.CoolWhip,
            ItemID.HamBat
        };

        public static readonly int[] PostMechWeapons = new int[35]
        {
            ItemID.Excalibur,
            ItemID.MagicalHarp,
            ItemID.RainbowRod,
            ItemID.Flamethrower,
            ItemID.Megashark,
            ItemID.Gungnir,
            ItemID.LightDisc,
            ItemID.HallowedRepeater,
            ItemID.TrueExcalibur,
            ItemID.TrueNightsEdge,
            ItemID.UnholyTrident,
            ItemID.MushroomSpear,
            ItemID.ChlorophyteClaymore,
            ItemID.ChlorophyteSaber,
            ItemID.ChlorophytePartisan,
            ItemID.ChlorophyteShotbow,
            ItemID.DeathSickle,
            ItemID.VenomStaff,
            ItemID.OpticStaff,
            ItemID.Code2,
            ItemID.Yelets,
            ItemID.RedsYoyo,
            ItemID.ValkyrieYoyo,
            ItemID.Arkhalis,
            ItemID.DD2FlameburstTowerT2Popper,
            ItemID.DD2SquireDemonSword,
            ItemID.DD2BallistraTowerT2Popper,
            ItemID.DD2LightningAuraT2Popper,
            ItemID.DD2ExplosiveTrapT2Popper,
            ItemID.MonkStaffT1,
            ItemID.MonkStaffT2,
            ItemID.BookStaff,
            ItemID.DD2PhoenixBow,
            ItemID.SwordWhip,
            ItemID.HallowJoustingLance
        };

        public static readonly int[] PostPlanteraWeapons = new int[54]
        {
            ItemID.Keybrand,
            ItemID.TerraBlade,
            ItemID.GrenadeLauncher,
            ItemID.RocketLauncher,
            ItemID.ProximityMineLauncher,
            ItemID.NettleBurst,
            ItemID.WaspGun,
            ItemID.PiranhaGun,
            ItemID.PygmyStaff,
            ItemID.LeafBlower,
            ItemID.SniperRifle,
            ItemID.VenusMagnum,
            ItemID.FlowerPow,
            ItemID.RainbowGun,
            ItemID.MagnetSphere,
            ItemID.ShadowbeamStaff,
            ItemID.InfernoFork,
            ItemID.SpectreStaff,
            ItemID.PaladinsHammer,
            ItemID.VampireKnives,
            ItemID.ScourgeoftheCorruptor,
            ItemID.StaffoftheFrostHydra,
            ItemID.CandyCornRifle,
            ItemID.JackOLanternLauncher,
            ItemID.BatScepter,
            ItemID.RavenStaff,
            ItemID.TheHorsemansBlade,
            ItemID.StakeLauncher,
            ItemID.EldMelter,
            ItemID.ChristmasTreeSword,
            ItemID.ChainGun,
            ItemID.Razorpine,
            ItemID.BlizzardStaff,
            ItemID.SnowmanCannon,
            ItemID.NorthPole,
            ItemID.PulseBow,
            ItemID.Seedler,
            ItemID.ToxicFlask,
            ItemID.PsychoKnife,
            ItemID.NailGun,
            ItemID.DeadlySphereStaff,
            ItemID.Kraken,
            ItemID.TheEyeOfCthulhu,
            ItemID.StormTigerStaff,
            ItemID.MaceWhip,
            ItemID.ScytheWhip,
            ItemID.SparkleGuitar,
            ItemID.ShadowJoustingLance,
            ItemID.RainbowWhip,
            ItemID.PiercingStarlight,
            ItemID.FairyQueenMagicItem,
            ItemID.FairyQueenRangedItem,
            ItemID.EmpressBlade,
            ItemID.PrincessWeapon
        };

        public static readonly int[] PostGolemWeapons = new int[40] {
            ItemID.PossessedHatchet,
            ItemID.HeatRay,
            ItemID.StaffofEarth,
            ItemID.GolemFist,
            ItemID.EldMelter,
            ItemID.ChristmasTreeSword,
            ItemID.ChainGun,
            ItemID.Razorpine,
            ItemID.BlizzardStaff,
            ItemID.SnowmanCannon,
            ItemID.NorthPole,
            ItemID.Flairon,
            ItemID.TempestStaff,
            ItemID.RazorbladeTyphoon,
            ItemID.BubbleGun,
            ItemID.Tsunami,
            ItemID.XenoStaff,
            ItemID.LaserMachinegun,
            ItemID.ElectrosphereLauncher,
            ItemID.Xenopopper,
            ItemID.InfluxWaver,
            ItemID.ChargedBlasterCannon,
            ItemID.SolarEruption,
            ItemID.StardustCellStaff,
            ItemID.VortexBeater,
            ItemID.NebulaArcanum,
            ItemID.StardustDragonStaff,
            ItemID.Phantasm,
            ItemID.NebulaBlaze,
            ItemID.DayBreak,
            ItemID.FireworksLauncher,
            ItemID.DD2FlameburstTowerT3Popper,
            ItemID.DD2BallistraTowerT3Popper,
            ItemID.DD2SquireBetsySword,
            ItemID.DD2LightningAuraT3Popper,
            ItemID.DD2ExplosiveTrapT3Popper,
            ItemID.MonkStaffT3,
            ItemID.DD2BetsyBow,
            ItemID.ApprenticeStaffT3,
            ItemID.EmpressBlade
        };

        public static readonly int[] Accessories = new int[105]
        {
            ItemID.Aglet,
            ItemID.AnkletoftheWind,
            ItemID.BalloonPufferfish,
            ItemID.BlizzardinaBottle,
            ItemID.ClimbingClaws,
            ItemID.CloudinaBottle,
            ItemID.SandBoots,
            ItemID.FartinaJar,
            ItemID.Flipper,
            ItemID.FlurryBoots,
            ItemID.FlyingCarpet,
            ItemID.FrogLeg,
            ItemID.HermesBoots,
            ItemID.IceSkates,
            ItemID.FloatingTube,
            ItemID.LavaCharm,
            ItemID.LuckyHorseshoe,
            ItemID.Magiluminescence,
            ItemID.NeptunesShell,
            ItemID.RocketBoots,
            ItemID.SailfishBoots,
            ItemID.SandstorminaBottle,
            ItemID.ShinyRedBalloon,
            ItemID.ShoeSpikes,
            ItemID.PortableStool,
            ItemID.Tabi,
            ItemID.TsunamiInABottle,
            ItemID.WaterWalkingBoots,
            ItemID.GPS,
            ItemID.REK,
            ItemID.GoblinTech,
            ItemID.FishFinder,
            ItemID.MechanicalLens,
            ItemID.BandofRegeneration,
            ItemID.BandofStarpower,
            ItemID.CelestialMagnet,
            ItemID.NaturesGift,
            ItemID.PhilosophersStone,
            ItemID.AdhesiveBandage,
            ItemID.ArmorPolish,
            ItemID.Bezoar,
            ItemID.BlackBelt,
            ItemID.Blindfold,
            ItemID.MoonCharm,
            ItemID.CobaltShield,
            ItemID.CrossNecklace,
            ItemID.EyeoftheGolem,
            ItemID.FastClock,
            ItemID.FeralClaws,
            ItemID.FleshKnuckles,
            ItemID.FrozenTurtleShell,
            ItemID.HandWarmer,
            ItemID.HoneyComb,
            ItemID.MagicQuiver,
            ItemID.MagmaStone,
            ItemID.Megaphone,
            ItemID.MoonStone,
            ItemID.Nazar,
            ItemID.ObsidianRose,
            ItemID.ObsidianSkull,
            ItemID.PaladinsShield,
            ItemID.PanicNecklace,
            ItemID.PocketMirror,
            ItemID.PutridScent,
            ItemID.RangerEmblem,
            ItemID.RifleScope,
            ItemID.Shackle,
            ItemID.SharkToothNecklace,
            ItemID.SorcererEmblem,
            ItemID.StarCloak,
            ItemID.SummonerEmblem,
            ItemID.SunStone,
            ItemID.TitanGlove,
            ItemID.TrifoldMap,
            ItemID.Vitamins,
            ItemID.WarriorEmblem,
            ItemID.ApprenticeScarf,
            ItemID.SquireShield,
            ItemID.HuntressBuckler,
            ItemID.MonkBelt,
            ItemID.HerculesBeetle,
            ItemID.NecromanticScroll,
            ItemID.PygmyNecklace,
            ItemID.AncientChisel,
            ItemID.HighTestFishingLine,
            ItemID.AnglerEarring,
            ItemID.TackleBox,
            ItemID.LavaFishingHook,
            ItemID.WhiteString,
            ItemID.BlackCounterweight,
            ItemID.YellowCounterweight,
            ItemID.BlueCounterweight,
            ItemID.RedCounterweight,
            ItemID.PurpleCounterweight,
            ItemID.GreenCounterweight,
            ItemID.YoYoGlove,
            ItemID.DiscountCard,
            ItemID.FlowerBoots,
            ItemID.GoldRing,
            ItemID.CordageGuide,
            ItemID.JellyfishNecklace,
            ItemID.LuckyCoin,
            ItemID.DontStarveShaderItem,
            ItemID.SpectreGoggles,
            ItemID.TreasureMagnet
        };

        public static readonly int[] Wings = new int[45]
        {
            ItemID.AngelWings,
            ItemID.DemonWings,
            ItemID.LeafWings,
            ItemID.FairyWings,
            ItemID.FinWings,
            ItemID.FrozenWings,
            ItemID.HarpyWings,
            ItemID.Jetpack,
            ItemID.FrostBreastplate,
            ItemID.DTownsWings,
            ItemID.WillsWings,
            ItemID.CrownosWings,
            ItemID.CenxsWings,
            ItemID.BejeweledValkyrieWing,
            ItemID.Yoraiz0rWings,
            ItemID.JimsWings,
            ItemID.SkiphsWings,
            ItemID.LokisWings,
            ItemID.ArkhalisWings,
            ItemID.LeinforsWings,
            ItemID.GhostarsWings,
            ItemID.SafemanWings,
            ItemID.FoodBarbarianWings,
            ItemID.GroxTheGreatWings,
            ItemID.BatWings,
            ItemID.BeeWings,
            ItemID.ButterflyWings,
            ItemID.FlameWings,
            ItemID.Hoverboard,
            ItemID.BoneWings,
            ItemID.MothronWings,
            ItemID.GhostWings,
            ItemID.BeetleWings,
            ItemID.FestiveWings,
            ItemID.SpookyWings,
            ItemID.TatteredFairyWings,
            ItemID.SteampunkWings,
            ItemID.BetsyWings,
            ItemID.RainbowWings,
            ItemID.FishronWings,
            ItemID.WingsNebula,
            ItemID.WingsVortex,
            ItemID.WingsSolar,
            ItemID.WingsStardust,
            ItemID.LongRainbowTrailWings
        };

        public static readonly int[] ExpertItems = new int[16]
        {
            ItemID.RoyalGel,
            ItemID.EoCShield,
            ItemID.WormScarf,
            ItemID.BrainOfConfusion,
            ItemID.HiveBackpack,
            ItemID.BoneGlove,
            ItemID.BoneHelm,
            ItemID.DemonHeart,
            ItemID.VolatileGelatin,
            ItemID.MinecartMech,
            ItemID.SporeSac,
            ItemID.ShinyStone,
            ItemID.EmpressFlightBooster,
            ItemID.ScalyTruffle,
            ItemID.GravityGlobe,
            ItemID.SuspiciousLookingTentacle
        };

        public static IItemDropRule[] JunkItems = new IItemDropRule[27]
        {
            ItemDropRule.Common(ItemID.AshBlock, minimumDropped: 50, maximumDropped: 75),
            ItemDropRule.Common(ItemID.BorealWoodSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Bunny, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Coal, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Confetti, minimumDropped: 10, maximumDropped: 50),
            ItemDropRule.Common(ItemID.DirtBlock, minimumDropped: 50, maximumDropped: 100),
            ItemDropRule.Common(ItemID.EbonwoodSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FlareGun, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Goldfish, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.LawnFlamingo, minimumDropped: 10, maximumDropped: 25),
            ItemDropRule.Common(ItemID.LovePotion, minimumDropped: 10, maximumDropped: 20),
            ItemDropRule.Common(ItemID.OldShoe, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.PalmWoodSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.PartyHat, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.PearlwoodSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.PearlwoodBow, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Pigronata, minimumDropped: 5, maximumDropped: 7),
            ItemDropRule.Common(ItemID.RichMahoganySword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.FishingSeaweed, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Seed, minimumDropped: 100, maximumDropped: 150),
            ItemDropRule.Common(ItemID.ShadewoodSword, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.SlimeGun, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.StinkPotion, minimumDropped: 10, maximumDropped: 20),
            ItemDropRule.Common(ItemID.TinCan, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.WaterGun, minimumDropped: 1, maximumDropped: 1),
            ItemDropRule.Common(ItemID.Wood, minimumDropped: 50, maximumDropped: 100),
            ItemDropRule.Common(ItemID.WoodenSword, minimumDropped: 1, maximumDropped: 1),
        };

        public static readonly Dictionary<int, IItemDropRule> AmmoWeapons = new Dictionary<int, IItemDropRule>
        {
            { ItemID.DemonBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.FlintlockPistol, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.Musket, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Minishark, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.IronBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Bone, ItemDropRule.Common(ItemID.Bone, minimumDropped: 69, maximumDropped: 119) },
            { ItemID.SpikyBall, ItemDropRule.Common(ItemID.SpikyBall, minimumDropped: 49, maximumDropped: 99) },
            { ItemID.Grenade, ItemDropRule.Common(ItemID.Grenade, minimumDropped: 19, maximumDropped: 49) },
            { ItemID.StarCannon, ItemDropRule.Common(ItemID.FallenStar, minimumDropped: 50, maximumDropped: 70) },
            { ItemID.Sandgun, ItemDropRule.Common(ItemID.SandBlock, minimumDropped: 30, maximumDropped: 70) },
            { ItemID.PoisonedKnife, ItemDropRule.Common(ItemID.PoisonedKnife, minimumDropped: 49, maximumDropped: 99) },
            { ItemID.ClockworkAssaultRifle, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.CobaltRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.MythrilRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.AdamantiteRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Flamethrower, ItemDropRule.Common(ItemID.Gel, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.Megashark, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Shotgun, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 20, maximumDropped: 40) },
            { ItemID.HallowedRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Marrow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.IceBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.GrenadeLauncher, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.RocketLauncher, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.ProximityMineLauncher, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.TendonBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.TheUndertaker, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Boomstick, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 20, maximumDropped: 40) },
            { ItemID.Blowgun, ItemDropRule.Common(ItemID.PoisonDart, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.Beenade, ItemDropRule.Common(ItemID.Beenade, minimumDropped: 9, maximumDropped: 29) },
            { ItemID.PalladiumRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.OrichalcumRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.TitaniumRepeater, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.ChlorophyteShotbow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.SniperRifle, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 20, maximumDropped: 30) },
            { ItemID.VenusMagnum, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.Uzi, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.SnowballCannon, ItemDropRule.Common(ItemID.Snowball, minimumDropped: 30, maximumDropped: 60) },
            { ItemID.CandyCornRifle, ItemDropRule.Common(ItemID.CandyCorn, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.JackOLanternLauncher, ItemDropRule.Common(ItemID.ExplosiveJackOLantern, minimumDropped: 25, maximumDropped: 50) },
            { ItemID.RottenEgg, ItemDropRule.Common(ItemID.RottenEgg, minimumDropped: 29, maximumDropped: 59) },
            { ItemID.StakeLauncher, ItemDropRule.Common(ItemID.Stake, minimumDropped: 30, maximumDropped: 60) },
            { ItemID.RedRyder, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.EldMelter, ItemDropRule.Common(ItemID.Gel, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.StarAnise, ItemDropRule.Common(ItemID.StarAnise, minimumDropped: 69, maximumDropped: 99) },
            { ItemID.ChainGun, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.SnowmanCannon, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 70, maximumDropped: 100) },
            { ItemID.PulseBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Revolver, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.Gatligator, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.MolotovCocktail, ItemDropRule.Common(ItemID.MolotovCocktail, minimumDropped: 19, maximumDropped: 49) },
            { ItemID.Tsunami, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.ElectrosphereLauncher, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 70, maximumDropped: 100) },
            { ItemID.Xenopopper, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.BeesKnees, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.DartPistol, ItemDropRule.Common(ItemID.PoisonDart, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.DartRifle, ItemDropRule.Common(ItemID.PoisonDart, minimumDropped: 30, maximumDropped: 50) },
            { ItemID.DaedalusStormbow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.ShadowFlameBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Javelin, ItemDropRule.Common(ItemID.Javelin, minimumDropped: 49, maximumDropped: 79) },
            { ItemID.NailGun, ItemDropRule.Common(ItemID.Nail, minimumDropped: 100, maximumDropped: 200) },
            { ItemID.BouncyGrenade, ItemDropRule.Common(ItemID.BouncyGrenade, minimumDropped: 19, maximumDropped: 39) },
            { ItemID.FrostDaggerfish, ItemDropRule.Common(ItemID.FrostDaggerfish, minimumDropped: 69, maximumDropped: 149) },
            { ItemID.BoneJavelin, ItemDropRule.Common(ItemID.BoneJavelin, minimumDropped: 19, maximumDropped: 49) },
            { ItemID.BoneDagger, ItemDropRule.Common(ItemID.BoneDagger, minimumDropped: 69, maximumDropped: 119) },
            { ItemID.VortexBeater, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.PlatinumBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.TungstenBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.LeadBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.TinBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.CopperBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.SilverBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.GoldBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.Phantasm, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.FireworksLauncher, ItemDropRule.Common(ItemID.RocketI, minimumDropped: 50, maximumDropped: 80) },
            { ItemID.PartyGirlGrenade, ItemDropRule.Common(ItemID.PartyGirlGrenade, minimumDropped: 19, maximumDropped: 49) },
            { ItemID.OnyxBlaster, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 20, maximumDropped: 40) },
            { ItemID.AleThrowingGlove, ItemDropRule.Common(ItemID.Ale, minimumDropped: 20, maximumDropped: 40) },
            { ItemID.DD2PhoenixBow,  ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped : 50, maximumDropped : 100) },
            { ItemID.DD2BetsyBow, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.PaperAirplaneA, ItemDropRule.Common(ItemID.PaperAirplaneA, minimumDropped: 19, maximumDropped: 39) },
            { ItemID.PaperAirplaneB, ItemDropRule.Common(ItemID.PaperAirplaneB, minimumDropped: 19, maximumDropped: 39) },
            { ItemID.FairyQueenRangedItem, ItemDropRule.Common(ItemID.WoodenArrow, minimumDropped: 50, maximumDropped: 100) },
            { ItemID.PewMaticHorn, ItemDropRule.Common(ItemID.MusketBall, minimumDropped: 50, maximumDropped: 80) }
        };
    }
}
